version: "3"
services:
  server:
    image: achat
    ports:
      - "8085:8085"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/achatdb?useSSL=false
    networks:
      - springmysql-net
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:5.7
    networks:
      - springmysql-net
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=achatdb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=

networks:
  springmysql-net:
  