version: "3.3"

services:
  angular-app:
    #The docker file in FE, builds and provides the docker image.
    image: nassimbenhassine/angularproject:latest
    ports:
      - 4200:4200 #Forwars the exposed port 4200 on the container to port 4200 on the host machine
    depends_on:
      - app
  mysqldb:
    image: mysql:latest
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE

    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    image:  nassimbenhassine/devops-nassim
    container_name: springboot-app
    restart: on-failure
    env_file: ./.env
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db: