version: "3.9"
services:

  mysql-db:
    image: mysql:8
    restart: unless-stopped
    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD= root
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    container_name: php-my-admin
    ports:
      - 8082:80
    environment:
      PMA_HOST: mysql-db

  spring_app:
    depends_on:
      - mysql-db
    image: nadiaouanes/achat
    container_name: achat
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/achatdb?useSSL=false",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "root",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    ports:
      - 9099:8090

volumes:
  db: