version: "3"
services:
  mysqldb:
    container_name: mysqldb
    image: mysql:8
    restart: unless-stopped
    environment: 
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - /home/mysql/data:/var/lib/mysql
      
  spring_app:
    image: achat
    container_name: achat
    restart: on-failure
    ports:
      - 9090:9090
    depends_on:
      - mysqldb
  